---
title: "PRA2"
author: "Marti Serra"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pràctica 2: Neteja i anàlisi de les dades

## 3. Neteja de les dades

### 3.1. Elements buits

```{r read}
df <- read.csv("winequality-red.csv")
summary(df)
```

### 3.2. Valors extrems

```{r boxplot}
par(mfrow = c(3, 4), mar = c(2, 5, 1, 1))
for (i in 1:length(df)) {
  boxplot(df[, i], main = names(df[i]), type = "l")
}
```

## 4. Anàlisi de les dades

### 4.2. Normalitat i homoscedastcititat

```{r shapiro}
sapply(seq(1, length(df)), function(x) {
  paste(colnames(df)[x],
        round(shapiro.test(df[, x])$p.value, 4),
        sep = ": ")
})
```

```{r fligner}
sapply(seq(1, length(df) - 1), function(x) {
  paste(colnames(df)[x],
        round(fligner.test(df[, x] ~ df[, 12])$p.value, 4),
        sep = ": ")
})
```

### 4.3. Proves estadístiques

```{r corr_df}
df_corr <- data.frame(
  Feature = character(),
  Qlt.Corr = double(),
  Qlt.Corr.p = double(),
  stringsAsFactors = FALSE
)
```

```{r corr_pearson}
for (col in c('citric.acid', 'residual.sugar', 'pH', 'sulphates')) {
  df_corr[nrow(df_corr) + 1,] =
    c(col,
      round(cor(df$quality, df[, col]), 4),
      round(cor.test(df$quality, df[, col])$p.value, 4))
}
```

```{r corr_spearman}
for (col in c(
  'fixed.acidity',
  'volatile.acidity',
  'chlorides',
  'free.sulfur.dioxide',
  'total.sulfur.dioxide',
  'density',
  'alcohol'
)) {
  df_corr[nrow(df_corr) + 1,] =
    c(col,
      round(cor(df$quality, df[, col],
                method = 'spearman'), 4),
      round(
        cor.test(df$quality, df[, col],
                 method = 'spearman', exact = FALSE)$p.value, 4))
}
```

```{r corr_results}
df_corr
```

```{r test_split}
qlt_med <- median(df$quality)
high_qlt_citric <- df[df$quality >= qlt_med, "citric.acid"]
low_qlt_citric <- df[df$quality < qlt_med, "citric.acid"]
c(length(high_qlt_citric), length(low_qlt_citric))
```

```{r test}
var.test(high_qlt_citric, low_qlt_citric)
```

```{r lm}
m1 <- glm(
  formula =
    quality
  ~ citric.acid
  + residual.sugar
  + pH
  + sulphates
  + fixed.acidity
  + volatile.acidity
  + chlorides
  + free.sulfur.dioxide
  + total.sulfur.dioxide
  + density
  + alcohol,
  data = df
)

summary(m1)
```

```{r lm2}
m2 <- glm(
  formula =
    quality
  ~ pH
  + sulphates
  + volatile.acidity
  + chlorides
  + free.sulfur.dioxide
  + total.sulfur.dioxide
  + alcohol,
  data = df
)

summary(m2)
```

```{r corr_full}
round(cor(df), 4)
```

## 6. Resolució del problema

```{r predict}
predict(
  m2,
  data.frame(
    pH = 3.51,
    sulphates = 0.56,
    volatile.acidity = 0.7,
    chlorides = 0.076,
    free.sulfur.dioxide = 11,
    total.sulfur.dioxide = 34,
    alcohol = 9.4
  )
)
```
